# docker compose for nginx
version: '3.1'

services:
  service:
    image: httpd:alpine3.18
    container_name: httpd
    restart: always
    networks:
      - nginx_network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - nginx_network

  # generate certs
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    command: certonly --webroot --webroot-path /var/www/certbot/ -d ${DOMAIN} --email ${EMAIL} --agree-tos --no-eff-email
    networks:
      - nginx_network
    depends_on:
      - nginx
    
networks:
  nginx_network:
    driver: bridge
